// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojfknvthcgrkfputezsc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qZmtudnRoY2dya2ZwdXRlenNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4ODEzNDgsImV4cCI6MjA3MDQ1NzM0OH0.9JJoHOxqwRAsYBCk0vYzl_bBoI2dVFpisWCri4A5C6c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});